### ISSUE TITLE
About Semantic-Aware Speech Tokenizer

### ISSUE THREAD

**Issue by xinkez** [FireRedTeam/FireRedTTS#3]
Hi,
Great Job!

I want to finetune the model unsing my own data. However, I don't find the Semantic-Aware Speech Tokenizer in your open-source codes. Do you plan to open-source the Semantic-Aware Speech Tokenizer with pretrained models?

Thanks in advance.

**Comment by FireRedTeam** [comment]
> Hi, Great Job!
> 
> I want to finetune the model unsing my own data. However, I don't find the Semantic-Aware Speech Tokenizer in your open-source codes. Do you plan to open-source the Semantic-Aware Speech Tokenizer with pretrained models?
> 
> Thanks in advance.

@xinkez our current goal is to bring more features to support different speech synthesis tasks for our users.  We will consider releasing the tokenizer if there is a strong demand (lots of users) for that :)

**Comment by sphmel** [comment]
@FireRedTeam +1

**Comment by hcwu1993** [comment]
@FireRedTeam +1

**Comment by janvainer** [comment]
@FireRedTeam +1

**Comment by Maple-se** [comment]
@FireRedTeam +1
