### ISSUE TITLE
是不是分句有问题

### ISSUE THREAD

**Issue by TheHonestBob** [FireRedTeam/FireRedTTS#4]
![image](https://github.com/user-attachments/assets/7fed9876-aef9-45ea-a8dc-e4bed72fd69d)
1. 如图，对于长句子会输出不合理的音频，
2. 似乎默认语速会很快，这是不是训练代码有bug，还是预料分布问题

**Comment by FireRedTeam** [comment]
> ![image](https://private-user-images.githubusercontent.com/58240629/371376416-7fed9876-aef9-45ea-a8dc-e4bed72fd69d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzMwNDUsIm5iZiI6MTcyODQ3Mjc0NSwicGF0aCI6Ii81ODI0MDYyOS8zNzEzNzY0MTYtN2ZlZDk4NzYtYWVmOS00NWVhLWE4ZGMtZTRiZWQ3MmZkNjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDExMTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2OTJhNGJiMjI2MWI5MzA1N2UyMDFmNjUzOWFmOGZkMDk4MWQyNjc3NjA4YzExMzZiOTNhMjExMmEwOWZiNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GpHdDrKNYx-Kwv4cTnLzut4_s8oPCJfBez_GT7_8cFs)
> 
> 1. 如图，对于长句子会输出不合理的音频，
> 2. 似乎默认语速会很快，这是不是训练代码有bug，还是预料分布问题

可以提供一下你的prompt_wav和对应文本吗？

**Comment by TheHonestBob** [comment]
> > ![image](https://private-user-images.githubusercontent.com/58240629/371376416-7fed9876-aef9-45ea-a8dc-e4bed72fd69d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzMwNDUsIm5iZiI6MTcyODQ3Mjc0NSwicGF0aCI6Ii81ODI0MDYyOS8zNzEzNzY0MTYtN2ZlZDk4NzYtYWVmOS00NWVhLWE4ZGMtZTRiZWQ3MmZkNjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDExMTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2OTJhNGJiMjI2MWI5MzA1N2UyMDFmNjUzOWFmOGZkMDk4MWQyNjc3NjA4YzExMzZiOTNhMjExMmEwOWZiNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GpHdDrKNYx-Kwv4cTnLzut4_s8oPCJfBez_GT7_8cFs)
> > 
> > 1. 如图，对于长句子会输出不合理的音频，
> > 2. 似乎默认语速会很快，这是不是训练代码有bug，还是预料分布问题
> 
> 可以提供一下你的prompt_wav和对应文本吗？
[zh_prompt.zip](https://github.com/user-attachments/files/17320375/zh_prompt.zip)

会议指出，今年我国气候年景偏差，强降雨过程多、历时长，江河洪水发生早、发展快，一些地方反复遭受强降雨冲击，防汛抗洪形势严峻复杂。在以习近平同志为核心的党中央坚强领导下，各级党委和政府迅速行动、全力应对，国家防总、各有关部门和单位履职尽责、通力协作，解放军和武警部队、国家综合性消防救援队伍和各类专业救援力量闻令而动、冲锋在前，广大干部群众风雨同舟、众志成城，共同构筑起了守护家园的坚固防线，防汛抗洪救灾取得重要阶段性成果。

**Comment by FireRedTeam** [comment]
是因为我们文本处理前端没有加入切句，对于超长文本会超过模型处理极限，**我们会尽快添加文本切句功能**。测试了下切分后的效果，应该是没有问题。
[1.wav.zip](https://github.com/user-attachments/files/17321474/1.wav.zip)

**Comment by FireRedTeam** [comment]
分句问题已经在新版中解决。
