### ISSUE TITLE
吞音鬼畜

### ISSUE THREAD

**Issue by martjay** [FireRedTeam/FireRedTTS#6]
比如说选中文带了数字或者某些符号，就会鬼畜，还有就是长段文字就会漏字，嗯，有很多问题

**Comment by FireRedTeam** [comment]
1. 因为训练语料的原因，某些符号可能不在我们的处理范围内，您可以手动处理一下。 
2. 我们会马上放出一个新模型来提升稳定性问题。

**Comment by martjay** [comment]
> 1. 因为训练语料的原因，某些符号可能不在我们的处理范围内，您可以手动处理一下。
> 
>     2. 我们会马上放出一个新模型来提升稳定性问题。

期待，还有一个问题就是句子末尾会缺字

**Comment by FireRedTeam** [comment]
也会一并解决

**Comment by FireRedTeam** [comment]
> 期待，还有一个问题就是句子末尾会缺字
新模型已经更新到huggingface了，使用最新模型即可

**Comment by FireRedTeam** [comment]
> 期待，还有一个问题就是句子末尾会缺字

新模型昨天已经更新到huggingface，使用最新模型即可

**Comment by martjay** [comment]
> > 期待，还有一个问题就是句子末尾会缺字
> 
> 新模型昨天已经更新到huggingface，使用最新模型即可

新鲜出炉的。

这几天不是开学了吗？

一朋友是做养殖场的，养的鸡是供当地烧烤店的。

这几天订单呈断崖式下沉，百思不得其解，后来跟其他行业的朋友聊起来，大家发现这几天整个消费市场突然间就一片死寂了，连警察朋友都说这几天大街上都突然冷清了一大截。

最后一寻思：开学了，交了各种费用后大家都没钱了。


https://github.com/user-attachments/assets/93186a81-71c7-45b1-a3ce-c81071c6abaa

还是会吞音

**Comment by martjay** [comment]
另外的问题就是生成速度慢，还有不稳定的错误

IndexError: index 0 is out of bounds for dimension 0 with size 0
Traceback (most recent call last):
  File "F:\AI\FireRedTTS-main\py311\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\FireRedTTS-main\py311\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\FireRedTTS-main\py311\Lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\FireRedTTS-main\py311\Lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\FireRedTTS-main\py311\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\FireRedTTS-main\py311\Lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "F:\AI\FireRedTTS-main\py311\Lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\FireRedTTS-main\py311\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "F:\AI\FireRedTTS-main\app.py", line 36, in tts_inference
    syn_audio_tensor = tts.synthesize(
                       ^^^^^^^^^^^^^^^
  File "F:\AI\FireRedTTS-main\fireredtts\fireredtts.py", line 142, in synthesize
    gpt_codes = self.do_gpt_inference(spk_gpt=spk_gpt, text_tokens=text_tokens)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\FireRedTTS-main\fireredtts\fireredtts.py", line 107, in do_gpt_inference
    index = (seq == EOS_TOKEN).nonzero(as_tuple=True)[0][0]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: index 0 is out of bounds for dimension 0 with size 0

**Comment by martjay** [comment]
上面的错误生成内容：

这家“汉丽轩自助烤肉”在济阳，2016年我在机场上班，下午5点下班，太阳还在半空中，就无所事事了，闲的蛋疼，就去附近的济阳转悠着玩。在中心广场上看到这家自助烤肉店。当时是39元一位，儿童半价，现在不知道多少钱了。菜品那是相当丰富，菜品得有上百个吧，还有各类肉片、海鲜等，各类饮料、甜点也很多。有烤炉、火锅。

**Comment by martjay** [comment]
最后就是建议多语言混合，分开确实不太好

**Comment by FireRedTeam** [comment]
> 另外的问题就是生成速度慢，还有不稳定的错误

这个也是因为你输入了过长的句子导致的，接下来一并解决。

**Comment by FireRedTeam** [comment]
> 最后就是建议多语言混合，分开确实不太好

多语言直接使用zh进行标签，不过你的建议收到，我们会逐步尝试把语言标签去掉。

**Comment by martjay** [comment]
> > 最后就是建议多语言混合，分开确实不太好
> 
> 多语言直接使用zh进行标签，不过你的建议收到，我们会逐步尝试把语言标签去掉。

好好好 等你们的好消息

**Comment by martjay** [comment]
> > 另外的问题就是生成速度慢，还有不稳定的错误
> 
> 这个也是因为你输入了过长的句子导致的，接下来一并解决。

大佬，进度如何了，吞音问题我估计是个大难题，从以前的tts项目来看

**Comment by FireRedTeam** [comment]
模型和代码已经更新

**Comment by martjay** [comment]
> 模型和代码已经更新

模型又更新了吗，我只看到一个11天前的模型更新了

**Comment by martjay** [comment]
> 模型和代码已经更新


> 模型和代码已经更新

更新代码后，我转了三段长字，包含数字的句子没发现鬼畜，但是后面还是会出现句子会被忽略，网易新闻的文字，希望能尽快解决。还有就是可以不用回车键生成，因为要编辑文字会用到。

**Comment by martjay** [comment]
> 模型和代码已经更新

我用了4天前发布的模型，仍然发现少量问题，比如《》这个符号，以及后面一句出现吞字，以及最后一段吞字：

先是21日，中金公司官宣达成了互换便利下的首笔质押式回购交易，质押券为2024年第一期互换便利央行票据；国泰君安则与中债信用增进公司签署《债券借贷协议》，并于21日完成首次交易相关的质押操作手续，以及交易前期相关配套工作。

22日，第一财经获悉，当日国泰君安完成互换便利下的全市场首单国债换入交易。中金公司也于当日在SFISF项下首次买入股票。据了解，国泰君安提交用于互换便利的首批质押资产为一揽子股票组合，后续将使用互换便利业务获得的资金进一步增持股票和股票ETF。

23日，国泰君安完成SFISF下的全市场首批国债质押式回购交易，质押券为互换便利操作借入的国债。
