### ISSUE TITLE
Too many bugs！！！

### ISSUE THREAD

**Issue by wen0320** [FireRedTeam/FireRedTTS#7]
First, thank you very much for your excellent model of open source. His effect is so good that I can't tell the synthetic speech from the real one. However, there are many bugs in the open source model. There are the following aspects：
1. The style of each phrase of the cloned speech is consistent with the style of the reference audio.
2. Some punctuation marks (? ,!) Or a special symbol (&*%$#^), which produces the wrong pronunciation.
3. Some short texts also have inexplicable errors, such as: 1. "呜呜..." . The result is a bunch of English. 2. "我...我也不知道呢"which synthesizes into" 我也不知道呢，我也不知道呢。"
4. At present, the open source model only supports the synthesis of 24KHz speech, hoping to open source 48KHz model.
5. And most importantly, can you open source and fine-tune your code? I want to build on that.

**Comment by wen0320** [comment]
Thank you very much for your. I look to the stable version.

**Comment by FireRedTeam** [comment]
> Thank you very much for your. I look to the stable version.

模型已经更新，使用最新模型即可，我们也会加强一下文本前端，去掉一些不发音的特殊符号。
